---
abstract: 'Layer to try to decrypt on read'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  File::Spec: '0'
  IO::Handle: '0'
  IPC::Open3: '0'
  Test::CheckDeps: '0.010'
  Test::More: '0.94'
  Test::Skip::UnlessExistsExecutable: '0'
  perl: '5.006'
configure_requires:
  ExtUtils::MakeMaker: '6.30'
dynamic_config: 0
generated_by: 'Dist::Zilla version 5.015, CPAN::Meta::Converter version 2.140640'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: PerlIO-via-GnuPG
no_index:
  directory:
    - corpus
    - t
provides:
  PerlIO::via::GnuPG:
    file: lib/PerlIO/via/GnuPG.pm
    version: '0.003'
  PerlIO::via::GnuPG::Maybe:
    file: lib/PerlIO/via/GnuPG/Maybe.pm
    version: '0.003'
requires:
  IPC::Open3: '0'
  Symbol: '0'
  parent: '0'
  perl: '5.006'
  strict: '0'
  warnings: '0'
resources:
  bugtracker: https://github.com/RsrchBoy/PerlIO-via-GnuPG/issues
  repository: git://github.com/RsrchBoy/PerlIO-via-GnuPG.git
version: '0.003'
x_Dist_Zilla:
  perl:
    version: '5.018002'
  plugins:
    -
      class: Dist::Zilla::Plugin::NextRelease
      name: '@RSRCHBOY/NextRelease'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::Git::NextVersion
      name: '@RSRCHBOY/Git::NextVersion'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::ContributorsFromGit
      name: '@RSRCHBOY/ContributorsFromGit'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::CorrectBranch
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::CorrectBranch'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::Fixups
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::Fixups'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::Git::CheckFor::MergeConflicts
      name: '@RSRCHBOY/@Git::CheckFor/Git::CheckFor::MergeConflicts'
      version: '0.009'
    -
      class: Dist::Zilla::Plugin::GatherDir
      name: '@RSRCHBOY/GatherDir'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::PromptIfStale
      config:
        Dist::Zilla::Plugin::PromptIfStale:
          check_all_plugins: 0
          check_all_prereqs: 0
          modules:
            - Dist::Zilla
            - Dist::Zilla::PluginBundle::RSRCHBOY
          phase: build
          skip: []
      name: '@RSRCHBOY/PromptIfStale'
      version: '0.021'
    -
      class: Dist::Zilla::Plugin::PruneCruft
      name: '@RSRCHBOY/PruneCruft'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::Git::Describe
      name: '@RSRCHBOY/Git::Describe'
      version: '0.003'
    -
      class: Dist::Zilla::Plugin::ExecDir
      name: '@RSRCHBOY/ExecDir'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::ShareDir
      name: '@RSRCHBOY/ShareDir'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::MakeMaker
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@RSRCHBOY/MakeMaker'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::InstallGuide
      name: '@RSRCHBOY/InstallGuide'
      version: '1.200002'
    -
      class: Dist::Zilla::Plugin::Manifest
      name: '@RSRCHBOY/Manifest'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::SurgicalPkgVersion
      name: '@RSRCHBOY/SurgicalPkgVersion'
      version: '0.0019'
    -
      class: Dist::Zilla::Plugin::ReadmeFromPod
      name: '@RSRCHBOY/ReadmeFromPod'
      version: '0.21'
    -
      class: Dist::Zilla::Plugin::MinimumPerl
      name: '@RSRCHBOY/MinimumPerl'
      version: '1.003'
    -
      class: Dist::Zilla::Plugin::ReportVersions::Tiny
      name: '@RSRCHBOY/ReportVersions::Tiny'
      version: '1.10'
    -
      class: Dist::Zilla::Plugin::AutoPrereqs
      name: '@RSRCHBOY/AutoPrereqs'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::Prepender
      name: '@RSRCHBOY/Prepender'
      version: '1.112280'
    -
      class: Dist::Zilla::Plugin::Test::PodSpelling
      name: '@RSRCHBOY/Test::PodSpelling'
      version: '2.006007'
    -
      class: Dist::Zilla::Plugin::ConsistentVersionTest
      name: '@RSRCHBOY/ConsistentVersionTest'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::PodCoverageTests
      name: '@RSRCHBOY/PodCoverageTests'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::PodSyntaxTests
      name: '@RSRCHBOY/PodSyntaxTests'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::NoTabsTests
      config:
        Dist::Zilla::Plugin::Test::NoTabs:
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@RSRCHBOY/NoTabsTests'
      version: '0.06'
    -
      class: Dist::Zilla::Plugin::EOLTests
      name: '@RSRCHBOY/EOLTests'
      version: '0.02'
    -
      class: Dist::Zilla::Plugin::HasVersionTests
      name: '@RSRCHBOY/HasVersionTests'
      version: '1.101420'
    -
      class: Dist::Zilla::Plugin::Test::Compile
      config:
        Dist::Zilla::Plugin::Test::Compile:
          filename: t/00-compile.t
          module_finder:
            - ':InstallModules'
          script_finder:
            - ':ExecFiles'
      name: '@RSRCHBOY/Test::Compile'
      version: '2.039'
    -
      class: Dist::Zilla::Plugin::NoSmartCommentsTests
      name: '@RSRCHBOY/NoSmartCommentsTests'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::Test::Pod::LinkCheck
      name: '@RSRCHBOY/Test::Pod::LinkCheck'
      version: '1.001'
    -
      class: Dist::Zilla::Plugin::RunExtraTests
      config:
        Dist::Zilla::Role::TestRunner:
          default_jobs: 1
      name: '@RSRCHBOY/RunExtraTests'
      version: '0.021'
    -
      class: Dist::Zilla::Plugin::CheckExtraTests
      name: '@RSRCHBOY/CheckExtraTests'
      version: '0.021'
    -
      class: Dist::Zilla::Plugin::Test::MinimumVersion
      name: '@RSRCHBOY/Test::MinimumVersion'
      version: '2.000005'
    -
      class: Dist::Zilla::Plugin::Authority
      name: '@RSRCHBOY/Authority'
      version: '1.006'
    -
      class: Dist::Zilla::Plugin::MetaConfig
      name: '@RSRCHBOY/MetaConfig'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::MetaJSON
      name: '@RSRCHBOY/MetaJSON'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::MetaYAML
      name: '@RSRCHBOY/MetaYAML'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::MetaNoIndex
      name: '@RSRCHBOY/MetaNoIndex'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::MetaProvides::Package
      config:
        Dist::Zilla::Plugin::MetaProvides::Package:
          finder_objects:
            -
              class: Dist::Zilla::Plugin::FinderCode
              name: '@RSRCHBOY/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
              version: '5.015'
        Dist::Zilla::Role::MetaProvider::Provider:
          inherit_missing: '1'
          inherit_version: '1'
          meta_noindex: '1'
      name: '@RSRCHBOY/MetaProvides::Package'
      version: '2.000001'
    -
      class: Dist::Zilla::Plugin::GitHub::Meta
      name: '@RSRCHBOY/GitHub::Meta'
      version: '0.36'
    -
      class: Dist::Zilla::Plugin::TestRelease
      name: '@RSRCHBOY/TestRelease'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::CheckChangesHasContent
      name: '@RSRCHBOY/CheckChangesHasContent'
      version: '0.006'
    -
      class: Dist::Zilla::Plugin::CheckPrereqsIndexed
      name: '@RSRCHBOY/CheckPrereqsIndexed'
      version: '0.010'
    -
      class: Dist::Zilla::Plugin::Git::Remote::Update
      name: '@RSRCHBOY/GitFetchOrigin'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: '@RSRCHBOY/GitCheckReleaseBranchSync'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::Remote::Check
      name: '@RSRCHBOY/GitCheckMasterBranchSync'
      version: 0.1.2
    -
      class: Dist::Zilla::Plugin::Git::Check
      name: '@RSRCHBOY/Git::Check'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Git::Commit
      name: '@RSRCHBOY/Git::Commit'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Test::CheckDeps
      name: '@RSRCHBOY/Test::CheckDeps'
      version: '0.012'
    -
      class: Dist::Zilla::Plugin::Travis::ConfigForReleaseBranch
      name: '@RSRCHBOY/Travis::ConfigForReleaseBranch'
      version: '0.001'
    -
      class: Dist::Zilla::Plugin::SchwartzRatio
      name: '@RSRCHBOY/SchwartzRatio'
      version: 0.2.0
    -
      class: Dist::Zilla::Plugin::Git::Tag
      name: '@RSRCHBOY/Git::Tag'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@RSRCHBOY/Git::CommitBuild::Build'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Git::CommitBuild
      name: '@RSRCHBOY/Git::CommitBuild::Release'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::Git::Push
      name: '@RSRCHBOY/Git::Push'
      version: '2.020'
    -
      class: Dist::Zilla::Plugin::UploadToCPAN
      name: '@RSRCHBOY/UploadToCPAN'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::Signature
      name: '@RSRCHBOY/Signature'
      version: '1.100930'
    -
      class: Dist::Zilla::Plugin::InstallRelease
      name: '@RSRCHBOY/InstallRelease'
      version: '0.008'
    -
      class: Dist::Zilla::Plugin::GitHub::Update
      name: '@RSRCHBOY/GitHub::Update'
      version: '0.36'
    -
      class: Dist::Zilla::Plugin::ArchiveRelease
      name: '@RSRCHBOY/ArchiveRelease'
      version: '4.00'
    -
      class: Dist::Zilla::Plugin::ConfirmRelease
      name: '@RSRCHBOY/ConfirmRelease'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::License
      name: '@RSRCHBOY/License'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::CPANFile
      name: '@RSRCHBOY/CPANFile'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::CopyFilesFromBuild
      name: '@RSRCHBOY/CopyFilesFromBuild'
      version: '0.103510'
    -
      class: Dist::Zilla::Plugin::ReadmeAnyFromPod
      name: '@RSRCHBOY/ReadmeMarkdownInRoot'
      version: '0.133360'
    -
      class: Dist::Zilla::Plugin::PodWeaver
      config:
        Dist::Zilla::Plugin::PodWeaver:
          config_plugins:
            - '@RSRCHBOY'
          finder:
            - ':InstallModules'
            - ':ExecFiles'
          plugins:
            -
              class: Pod::Weaver::Plugin::StopWords
              name: '@RSRCHBOY/StopWords'
              version: '1.008'
            -
              class: Pod::Weaver::Plugin::EnsurePod5
              name: '@CorePrep/EnsurePod5'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::H1Nester
              name: '@CorePrep/H1Nester'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Name
              name: '@RSRCHBOY/Name'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Version
              name: '@RSRCHBOY/Version'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@RSRCHBOY/prelude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: SYNOPSIS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: DESCRIPTION
              version: '4.006'
            -
              class: Pod::Weaver::Section::Generic
              name: OVERVIEW
              version: '4.006'
            -
              class: Pod::Weaver::Section::RSRCHBOY::RoleParameters
              name: 'ROLE PARAMETERS'
              version: '0.044'
            -
              class: Pod::Weaver::Section::RSRCHBOY::RequiredAttributes
              name: 'REQUIRED ATTRIBUTES'
              version: '0.044'
            -
              class: Pod::Weaver::Section::RSRCHBOY::LazyAttributes
              name: 'LAZY ATTRIBUTES'
              version: '0.044'
            -
              class: Pod::Weaver::Section::Collect
              name: ATTRIBUTES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: METHODS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: 'REQUIRED METHODS'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: FUNCTIONS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: TYPES
              version: '4.006'
            -
              class: Pod::Weaver::Section::Collect
              name: TEST_FUNCTIONS
              version: '4.006'
            -
              class: Pod::Weaver::Section::Leftovers
              name: '@RSRCHBOY/Leftovers'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Region
              name: '@RSRCHBOY/postlude'
              version: '4.006'
            -
              class: Pod::Weaver::Section::SeeAlso
              name: '@RSRCHBOY/SeeAlso'
              version: '1.002'
            -
              class: Pod::Weaver::Section::SourceGitHub
              name: '@RSRCHBOY/SourceGitHub'
              version: '0.54'
            -
              class: Pod::Weaver::Section::Bugs
              name: '@RSRCHBOY/Bugs'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Authors
              name: '@RSRCHBOY/Authors'
              version: '4.006'
            -
              class: Pod::Weaver::Section::Contributors
              name: '@RSRCHBOY/Contributors'
              version: '0.007'
            -
              class: Pod::Weaver::Section::Legal
              name: '@RSRCHBOY/Legal'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::Transformer
              name: '@RSRCHBOY/List'
              version: '4.006'
            -
              class: Pod::Weaver::Plugin::Encoding
              name: '@RSRCHBOY/Encoding'
              version: '0.02'
      name: '@RSRCHBOY/PodWeaver'
      version: '4.005'
    -
      class: Dist::Zilla::Plugin::Encoding
      name: Encoding
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':InstallModules'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':IncModules'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':TestFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ExecFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':ShareFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':MainModule'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':AllFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: ':NoFiles'
      version: '5.015'
    -
      class: Dist::Zilla::Plugin::FinderCode
      name: '@RSRCHBOY/MetaProvides::Package/AUTOVIV/:InstallModulesPM'
      version: '5.015'
  zilla:
    class: Dist::Zilla::Dist::Builder
    config:
      is_trial: '0'
    version: '5.015'
x_authority: cpan:RSRCHBOY
